-- MASTER SCHEMA UPDATE SCRIPT
-- WARNING: This script will drop existing tables and recreate them to match the new strict specification.
-- DATA LOSS WARNING: Existing data in 'students', 'classes', 'subjects', 'schedules' will be lost.

BEGIN;

-- 1. DROP EXISTING TABLES (CASCADE to remove foreign keys)
DROP TABLE IF EXISTS public.activity_logs CASCADE;
DROP TABLE IF EXISTS public.points_log CASCADE; -- Old table
DROP TABLE IF EXISTS public.attendance CASCADE; -- Old table
DROP TABLE IF EXISTS public.schedules CASCADE; -- Old table
DROP TABLE IF EXISTS public.subjects CASCADE; -- Old table
DROP TABLE IF EXISTS public.students CASCADE; -- Old table
DROP TABLE IF EXISTS public.classes CASCADE; -- Old table
DROP TABLE IF EXISTS public.profiles CASCADE; -- Old table
DROP TABLE IF EXISTS public.users CASCADE; -- New table name conflict check
DROP TABLE IF EXISTS public.siswa CASCADE;
DROP TABLE IF EXISTS public.kelas CASCADE;
DROP TABLE IF EXISTS public.mata_pelajaran CASCADE;
DROP TABLE IF EXISTS public.jadwal_kelas CASCADE;
DROP TABLE IF EXISTS public.absensi CASCADE;
DROP TABLE IF EXISTS public.poin_prestasi CASCADE;
DROP TABLE IF EXISTS public.poin_pelanggaran CASCADE;
DROP TABLE IF EXISTS public.poin_kategori CASCADE;
DROP TABLE IF EXISTS public.semester CASCADE;
DROP TABLE IF EXISTS public.tahun_ajaran CASCADE;
DROP TABLE IF EXISTS public.aktivitas_siswa CASCADE;
DROP TABLE IF EXISTS public.settings CASCADE;
DROP TABLE IF EXISTS public.notifications CASCADE;
DROP TABLE IF EXISTS public.jam_pelajaran CASCADE;

-- 2. CREATE ENUMS
DO $$ BEGIN
    CREATE TYPE jenis_kelamin_enum AS ENUM ('L', 'P');
    CREATE TYPE user_role_enum AS ENUM ('admin', 'guru', 'siswa');
    CREATE TYPE user_status_enum AS ENUM ('aktif', 'nonaktif', 'pensiun', 'pindah');
    CREATE TYPE siswa_status_enum AS ENUM ('aktif', 'alumni', 'pindah', 'keluar', 'dropout');
    CREATE TYPE kelas_tingkat_enum AS ENUM ('X', 'XI', 'XII');
    CREATE TYPE semester_enum AS ENUM ('ganjil', 'genap');
    CREATE TYPE kelas_status_enum AS ENUM ('aktif', 'nonaktif');
    CREATE TYPE mapel_kategori_enum AS ENUM ('umum', 'jurusan', 'peminatan', 'ekstrakurikuler');
    CREATE TYPE mapel_tingkat_enum AS ENUM ('X', 'XI', 'XII', 'semua');
    CREATE TYPE mapel_semester_enum AS ENUM ('ganjil', 'genap', 'tahunan');
    CREATE TYPE mapel_status_enum AS ENUM ('aktif', 'nonaktif');
    CREATE TYPE jam_jenis_enum AS ENUM ('normal', 'istirahat', 'upacara', 'khusus');
    CREATE TYPE hari_enum AS ENUM ('Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu', 'semua');
    CREATE TYPE jam_status_enum AS ENUM ('aktif', 'nonaktif');
    CREATE TYPE jadwal_hari_enum AS ENUM ('Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu');
    CREATE TYPE jadwal_status_enum AS ENUM ('aktif', 'nonaktif');
    CREATE TYPE absensi_status_enum AS ENUM ('hadir', 'sakit', 'izin', 'alfa', 'terlambat', 'dinas', 'cuti');
    CREATE TYPE absensi_metode_enum AS ENUM ('manual', 'qr_code', 'fingerprint', 'face_recognition');
    CREATE TYPE prestasi_jenis_enum AS ENUM ('akademik', 'non-akademik', 'sosial', 'olahraga', 'seni', 'lainnya');
    CREATE TYPE prestasi_kategori_enum AS ENUM ('prestasi', 'penghargaan', 'lomba', 'kejuaraan');
    CREATE TYPE prestasi_tingkat_enum AS ENUM ('sekolah', 'kecamatan', 'kabupaten', 'provinsi', 'nasional', 'internasional');
    CREATE TYPE prestasi_peringkat_enum AS ENUM ('juara_1', 'juara_2', 'juara_3', 'harapan', 'partisipasi');
    CREATE TYPE prestasi_status_enum AS ENUM ('pending', 'approved', 'rejected');
    CREATE TYPE pelanggaran_jenis_enum AS ENUM ('ringan', 'sedang', 'berat');
    CREATE TYPE pelanggaran_status_enum AS ENUM ('pending', 'ditindak', 'selesai');
    CREATE TYPE kategori_jenis_enum AS ENUM ('prestasi', 'pelanggaran');
    CREATE TYPE kategori_status_enum AS ENUM ('aktif', 'nonaktif');
    CREATE TYPE semester_status_enum AS ENUM ('aktif', 'selesai', 'akan_datang');
    CREATE TYPE tahun_ajaran_status_enum AS ENUM ('aktif', 'selesai', 'akan_datang');
    CREATE TYPE aktivitas_jenis_enum AS ENUM ('absensi', 'prestasi', 'pelanggaran', 'perubahan_data', 'lainnya');
    CREATE TYPE setting_type_enum AS ENUM ('text', 'number', 'boolean', 'json', 'date', 'time');
    CREATE TYPE notif_type_enum AS ENUM ('info', 'warning', 'success', 'danger');
EXCEPTION
    WHEN duplicate_object THEN null;
END $$;

-- 3. CREATE TABLES

-- TABEL 1: USERS (Admin & Guru)
CREATE TABLE public.users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    nama_lengkap VARCHAR(100) NOT NULL,
    jenis_kelamin jenis_kelamin_enum DEFAULT 'L',
    nip VARCHAR(30) UNIQUE,
    tempat_lahir VARCHAR(50),
    tanggal_lahir DATE,
    alamat TEXT,
    no_telepon VARCHAR(15),
    email VARCHAR(100) UNIQUE,
    role user_role_enum DEFAULT 'guru',
    jabatan VARCHAR(100),
    bidang_studi VARCHAR(100),
    foto VARCHAR(255),
    status user_status_enum DEFAULT 'aktif',
    last_login TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 3: KELAS (Dibuat sebelum SISWA karena ada relasi)
CREATE TABLE public.kelas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_kelas VARCHAR(10) UNIQUE NOT NULL,
    nama_kelas VARCHAR(50) NOT NULL,
    tingkat kelas_tingkat_enum NOT NULL,
    jurusan VARCHAR(50),
    wali_kelas_id INT REFERENCES public.users(id) ON DELETE SET NULL,
    kapasitas INT DEFAULT 30,
    ruangan VARCHAR(20),
    tahun_ajaran VARCHAR(9),
    semester semester_enum DEFAULT 'ganjil',
    status kelas_status_enum DEFAULT 'aktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 2: SISWA
CREATE TABLE public.siswa (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nis VARCHAR(20) UNIQUE NOT NULL,
    nisn VARCHAR(20) UNIQUE NOT NULL,
    nama_lengkap VARCHAR(100) NOT NULL,
    jenis_kelamin jenis_kelamin_enum NOT NULL,
    tempat_lahir VARCHAR(50),
    tanggal_lahir DATE,
    agama VARCHAR(20),
    alamat TEXT,
    rt_rw VARCHAR(10),
    kelurahan VARCHAR(50),
    kecamatan VARCHAR(50),
    kota VARCHAR(50),
    provinsi VARCHAR(50),
    kode_pos VARCHAR(10),
    no_telepon VARCHAR(15),
    email VARCHAR(100),
    nama_ayah VARCHAR(100),
    nama_ibu VARCHAR(100),
    pekerjaan_ayah VARCHAR(100),
    pekerjaan_ibu VARCHAR(100),
    no_telepon_ortu VARCHAR(15),
    kelas_id INT REFERENCES public.kelas(id) ON DELETE SET NULL,
    foto VARCHAR(255),
    status siswa_status_enum DEFAULT 'aktif',
    tahun_masuk INT, -- YEAR type maps to INT or smallint usually, INT is safe
    tahun_keluar INT,
    total_poin_prestasi INT DEFAULT 0,
    total_poin_pelanggaran INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 4: MATA_PELAJARAN
CREATE TABLE public.mata_pelajaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    kode_mapel VARCHAR(10) UNIQUE NOT NULL,
    nama_mapel VARCHAR(100) NOT NULL,
    kategori mapel_kategori_enum DEFAULT 'umum',
    tingkat mapel_tingkat_enum DEFAULT 'semua',
    jurusan VARCHAR(50),
    guru_id INT REFERENCES public.users(id) ON DELETE SET NULL,
    kelas_id INT REFERENCES public.kelas(id) ON DELETE CASCADE, -- Relation noted in spec
    semester mapel_semester_enum DEFAULT 'tahunan',
    tahun_ajaran VARCHAR(9),
    jam_per_minggu INT DEFAULT 2,
    deskripsi TEXT,
    status mapel_status_enum DEFAULT 'aktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 5: JAM_PELAJARAN
CREATE TABLE public.jam_pelajaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sesi INT NOT NULL,
    jam_mulai TIME NOT NULL,
    jam_selesai TIME NOT NULL,
    keterangan VARCHAR(50),
    jenis jam_jenis_enum DEFAULT 'normal',
    hari hari_enum DEFAULT 'semua',
    status jam_status_enum DEFAULT 'aktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 6: JADWAL_KELAS
CREATE TABLE public.jadwal_kelas (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hari jadwal_hari_enum NOT NULL,
    sesi INT NOT NULL,
    mapel_id INT REFERENCES public.mata_pelajaran(id) ON DELETE CASCADE,
    kelas_id INT REFERENCES public.kelas(id) ON DELETE CASCADE,
    guru_id INT REFERENCES public.users(id) ON DELETE CASCADE,
    ruangan VARCHAR(20),
    tahun_ajaran VARCHAR(9),
    semester semester_enum DEFAULT 'ganjil',
    status jadwal_status_enum DEFAULT 'aktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_jadwal UNIQUE(hari, sesi, kelas_id, tahun_ajaran, semester)
);

-- TABEL 7: ABSENSI
CREATE TABLE public.absensi (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id INT REFERENCES public.siswa(id) ON DELETE CASCADE,
    mapel_id INT REFERENCES public.mata_pelajaran(id) ON DELETE CASCADE,
    tanggal DATE NOT NULL,
    sesi INT NOT NULL,
    status absensi_status_enum DEFAULT 'alfa',
    keterangan TEXT,
    waktu_absen TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    guru_id INT REFERENCES public.users(id) ON DELETE SET NULL,
    metode_absen absensi_metode_enum DEFAULT 'manual',
    latitude DECIMAL(10,8),
    longitude DECIMAL(11,8),
    bukti_izin VARCHAR(255),
    verified_by INT REFERENCES public.users(id) ON DELETE SET NULL,
    verified_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_absensi UNIQUE(siswa_id, mapel_id, tanggal, sesi)
);

-- TABEL 8: POIN_PRESTASI
CREATE TABLE public.poin_prestasi (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id INT REFERENCES public.siswa(id) ON DELETE CASCADE,
    jenis_prestasi prestasi_jenis_enum DEFAULT 'akademik',
    kategori prestasi_kategori_enum DEFAULT 'prestasi',
    nama_prestasi VARCHAR(200) NOT NULL,
    deskripsi TEXT,
    tingkat prestasi_tingkat_enum NOT NULL,
    peringkat prestasi_peringkat_enum DEFAULT 'partisipasi',
    poin INT NOT NULL,
    tanggal DATE NOT NULL,
    penyelenggara VARCHAR(100),
    lokasi VARCHAR(100),
    keterangan TEXT,
    dokumen VARCHAR(255),
    foto VARCHAR(255),
    created_by INT REFERENCES public.users(id) ON DELETE SET NULL,
    status prestasi_status_enum DEFAULT 'pending',
    approved_by INT REFERENCES public.users(id) ON DELETE SET NULL,
    approved_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 9: POIN_PELANGGARAN
CREATE TABLE public.poin_pelanggaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id INT REFERENCES public.siswa(id) ON DELETE CASCADE,
    jenis_pelanggaran pelanggaran_jenis_enum NOT NULL,
    kategori_pelanggaran VARCHAR(100),
    deskripsi TEXT NOT NULL,
    poin INT NOT NULL,
    tanggal DATE NOT NULL,
    sanksi TEXT,
    lokasi VARCHAR(100),
    saksi VARCHAR(100),
    ditindak_oleh INT REFERENCES public.users(id) ON DELETE SET NULL,
    status pelanggaran_status_enum DEFAULT 'pending',
    tindak_lanjut TEXT,
    follow_up_by INT REFERENCES public.users(id) ON DELETE SET NULL,
    follow_up_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 10: POIN_KATEGORI
CREATE TABLE public.poin_kategori (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    jenis kategori_jenis_enum NOT NULL,
    nama_kategori VARCHAR(100) NOT NULL,
    deskripsi TEXT,
    poin_min INT DEFAULT 0,
    poin_max INT DEFAULT 0,
    sanksi TEXT,
    penghargaan TEXT,
    status kategori_status_enum DEFAULT 'aktif',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 11: SEMESTER
CREATE TABLE public.semester (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun_ajaran VARCHAR(9) NOT NULL,
    semester semester_enum NOT NULL,
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status semester_status_enum DEFAULT 'akan_datang',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT unique_semester UNIQUE(tahun_ajaran, semester)
);

-- TABEL 12: TAHUN_AJARAN
CREATE TABLE public.tahun_ajaran (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tahun_ajaran VARCHAR(9) UNIQUE NOT NULL,
    tanggal_mulai DATE NOT NULL,
    tanggal_selesai DATE NOT NULL,
    status tahun_ajaran_status_enum DEFAULT 'akan_datang',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 13: AKTIVITAS_SISWA
CREATE TABLE public.aktivitas_siswa (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    siswa_id INT REFERENCES public.siswa(id) ON DELETE CASCADE,
    jenis_aktivitas aktivitas_jenis_enum NOT NULL,
    deskripsi TEXT NOT NULL,
    tanggal DATE NOT NULL,
    waktu TIME NOT NULL,
    created_by INT REFERENCES public.users(id) ON DELETE SET NULL,
    referensi_id INT,
    referensi_tabel VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 14: SETTINGS
CREATE TABLE public.settings (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key VARCHAR(100) UNIQUE NOT NULL,
    setting_value TEXT,
    setting_group VARCHAR(50) DEFAULT 'general',
    setting_type setting_type_enum DEFAULT 'text',
    label VARCHAR(100),
    description TEXT,
    options TEXT,
    is_public BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 15: ACTIVITY_LOGS (Re-created linked to users)
CREATE TABLE public.activity_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES public.users(id) ON DELETE CASCADE,
    activity VARCHAR(255) NOT NULL,
    module VARCHAR(50),
    action VARCHAR(50),
    details TEXT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    referrer VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- TABEL 16: NOTIFICATIONS
CREATE TABLE public.notifications (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES public.users(id) ON DELETE CASCADE,
    title VARCHAR(200) NOT NULL,
    message TEXT NOT NULL,
    type notif_type_enum DEFAULT 'info',
    is_read BOOLEAN DEFAULT FALSE,
    link VARCHAR(255),
    data JSON,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    read_at TIMESTAMP
);

-- ENABLE RLS (Row Level Security) ON ALL TABLES
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.mata_pelajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jam_pelajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.jadwal_kelas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.absensi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poin_prestasi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poin_pelanggaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.poin_kategori ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.semester ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tahun_ajaran ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.aktivitas_siswa ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;

-- CREATE GENERIC RLS POLICIES (Allow All for Dev/Simplification as per previous requests)
-- Note: In production, these should be much stricter based on 'role'.
CREATE POLICY "Allow All Access" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.siswa FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.kelas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.mata_pelajaran FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.jam_pelajaran FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.jadwal_kelas FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.absensi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.poin_prestasi FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.poin_pelanggaran FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.poin_kategori FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.semester FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.tahun_ajaran FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.aktivitas_siswa FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.settings FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.activity_logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow All Access" ON public.notifications FOR ALL USING (true) WITH CHECK (true);

COMMIT;
