-- COMPREHENSIVE ACTIVITY LOGGING SETUP
-- Aligns with master_schema_update.sql structure

BEGIN;

-- 1. Ensure activity_logs table exists and has correct columns (idempotent)
CREATE TABLE IF NOT EXISTS public.activity_logs (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT REFERENCES public.users(id) ON DELETE CASCADE,
    activity VARCHAR(255) NOT NULL,
    module VARCHAR(50),
    action VARCHAR(50),
    details TEXT,
    ip_address VARCHAR(45),
    user_agent TEXT,
    referrer VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. Create the Trigger Function
CREATE OR REPLACE FUNCTION public.log_data_change()
RETURNS TRIGGER AS $$
DECLARE
    current_app_user_id INT;
    record_identifier TEXT;
    log_activity_text TEXT;
    log_details TEXT;
BEGIN
    -- Attempt to identify the app user based on the Auth user (if logged in via various means)
    -- This relies on matching Email, which is a common link.
    BEGIN
        SELECT id INTO current_app_user_id
        FROM public.users
        WHERE email = (SELECT email FROM auth.users WHERE id = auth.uid())
        LIMIT 1;
    EXCEPTION WHEN OTHERS THEN
        current_app_user_id := NULL;
    END;

    -- Determine Identifier based on table
    IF (TG_TABLE_NAME = 'users') THEN
        record_identifier := COALESCE(NEW.nama_lengkap, OLD.nama_lengkap);
    ELSIF (TG_TABLE_NAME = 'siswa') THEN
        record_identifier := COALESCE(NEW.nama_lengkap, OLD.nama_lengkap);
    ELSIF (TG_TABLE_NAME = 'kelas') THEN
        record_identifier := COALESCE(NEW.nama_kelas, OLD.nama_kelas);
    ELSIF (TG_TABLE_NAME = 'mata_pelajaran') THEN
        record_identifier := COALESCE(NEW.nama_mapel, OLD.nama_mapel);
    ELSE
        record_identifier := 'ID: ' || COALESCE(NEW.id, OLD.id)::TEXT;
    END IF;

    -- Format Log Message
    log_activity_text := TG_OP || ' on ' || TG_TABLE_NAME || ': ' || record_identifier;
    
    -- Format Details (JSON dump of change)
    IF (TG_OP = 'INSERT') THEN
        log_details := row_to_json(NEW)::TEXT;
    ELSIF (TG_OP = 'UPDATE') THEN
        log_details := 'Changes: ' || (row_to_json(NEW)::jsonb - row_to_json(OLD)::jsonb)::TEXT;
    ELSIF (TG_OP = 'DELETE') THEN
        log_details := row_to_json(OLD)::TEXT;
    END IF;

    -- Insert Log
    INSERT INTO public.activity_logs (
        user_id, 
        activity, 
        module, 
        action, 
        details
    ) VALUES (
        current_app_user_id,
        log_activity_text,
        TG_TABLE_NAME,
        TG_OP,
        log_details
    );

    RETURN NULL;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- 3. Apply Triggers to All Tables
-- Drop existing first to avoid duplicates
DROP TRIGGER IF EXISTS trg_log_users ON public.users;
CREATE TRIGGER trg_log_users AFTER INSERT OR UPDATE OR DELETE ON public.users FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_siswa ON public.siswa;
CREATE TRIGGER trg_log_siswa AFTER INSERT OR UPDATE OR DELETE ON public.siswa FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_kelas ON public.kelas;
CREATE TRIGGER trg_log_kelas AFTER INSERT OR UPDATE OR DELETE ON public.kelas FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_mata_pelajaran ON public.mata_pelajaran;
CREATE TRIGGER trg_log_mata_pelajaran AFTER INSERT OR UPDATE OR DELETE ON public.mata_pelajaran FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_jadwal_kelas ON public.jadwal_kelas;
CREATE TRIGGER trg_log_jadwal_kelas AFTER INSERT OR UPDATE OR DELETE ON public.jadwal_kelas FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_absensi ON public.absensi;
CREATE TRIGGER trg_log_absensi AFTER INSERT OR UPDATE OR DELETE ON public.absensi FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_poin_prestasi ON public.poin_prestasi;
CREATE TRIGGER trg_log_poin_prestasi AFTER INSERT OR UPDATE OR DELETE ON public.poin_prestasi FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_poin_pelanggaran ON public.poin_pelanggaran;
CREATE TRIGGER trg_log_poin_pelanggaran AFTER INSERT OR UPDATE OR DELETE ON public.poin_pelanggaran FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_tahun_ajaran ON public.tahun_ajaran;
CREATE TRIGGER trg_log_tahun_ajaran AFTER INSERT OR UPDATE OR DELETE ON public.tahun_ajaran FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

DROP TRIGGER IF EXISTS trg_log_settings ON public.settings;
CREATE TRIGGER trg_log_settings AFTER INSERT OR UPDATE OR DELETE ON public.settings FOR EACH ROW EXECUTE FUNCTION public.log_data_change();

COMMIT;
